base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
append_commit_message: false
commit_message: 'New translations: %original_file_name% (%language%)'
files:
  - source: /translation/source/*.json
    translation: /translation/dest/%file_name%/%locale%.%file_extension%
    update_option: update_without_changes
